"""upgrade tables'

Revision ID: 7e1e7e5f650f
Revises: e028fdc7dd0f
Create Date: 2024-07-20 22:44:14.375583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1e7e5f650f'
down_revision: Union[str, None] = 'e028fdc7dd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'date')
    # ### end Alembic commands ###
